# Generated by Django 4.2.5 on 2023-10-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_userprofile_friends_userprofile_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default=0, upload_to='covers/None_<built-in function id>'),
            preserve_default=False,
        ),
    ]
