# Generated by Django 4.2.5 on 2023-11-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_message_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='recent_message_owner',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
