# Generated by Django 4.2.5 on 2023-11-05 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_chat_recent_message_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created']},
        ),
    ]
