# Generated by Django 4.2.5 on 2023-11-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-created', '-updated']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created', '-updated']},
        ),
    ]
